elfin_arm_controller:
  type: pos_vel_controllers/JointTrajectoryController
  # position_controllers
  # elfin_pos_trq_controllers
  # pos_vel_controllers
  joints:
     - elfin_joint1
     - elfin_joint2
     - elfin_joint3
     - elfin_joint4
     - elfin_joint5
     - elfin_joint6
  velocity_ff:
    elfin_joint1: 1
    elfin_joint2: 1
    elfin_joint3: 1
    elfin_joint4: 1
    elfin_joint5: 1
    elfin_joint6: 1
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1
  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10
